[2024-06-20T16:23:10.803200+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:23:10.810429+00:00] app.ERROR: An exception occurred in Default scenario {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/doc\" is not callable: Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:98)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"nelmio_api_doc.controller.swagger_ui\" not found at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:153)"} []
[2024-06-20T16:40:31.684977+00:00] app.INFO: HttpException {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/\" at /app/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:181)"} []
[2024-06-20T16:40:31.835047+00:00] app.INFO: HttpException {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/favicon.ico\" (from \"http://localhost/\") at /app/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2024-06-20T16:40:39.731407+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:40:39.737859+00:00] app.ERROR: An exception occurred in Default scenario {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/doc\" is not callable: Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:98)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"nelmio_api_doc.controller.swagger_ui\" not found at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:153)"} []
[2024-06-20T16:42:10.161857+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:42:10.166974+00:00] app.ERROR: An exception occurred in Default scenario {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/doc\" is not callable: Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:98)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"nelmio_api_doc.controller.swagger_ui\" not found at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:153)"} []
[2024-06-20T16:42:12.167274+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:42:12.172097+00:00] app.ERROR: An exception occurred in Default scenario {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/doc\" is not callable: Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:98)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"nelmio_api_doc.controller.swagger_ui\" not found at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:153)"} []
[2024-06-20T16:42:18.511288+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:42:18.515733+00:00] app.ERROR: An exception occurred in Default scenario {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/doc\" is not callable: Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:98)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"nelmio_api_doc.controller.swagger_ui\" not found at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:153)"} []
[2024-06-20T16:42:21.023491+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:42:21.028346+00:00] app.ERROR: An exception occurred in Default scenario {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/doc\" is not callable: Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:98)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"nelmio_api_doc.controller.swagger_ui\" not found at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:153)"} []
[2024-06-20T16:43:04.389794+00:00] app.INFO: HttpException {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/\" at /app/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:181)"} []
[2024-06-20T16:43:27.557887+00:00] request.INFO: Matched route "price". {"route":"price","route_parameters":{"_route":"price","_controller":"App\\Controller\\PriceController::index"},"request_uri":"http://localhost/api/price","method":"GET"} []
[2024-06-20T16:43:27.629558+00:00] app.INFO: An exception occurred in ValidationException scenario {"exception":"[object] (App\\Exception\\ValidationException(code: 0): Request validation failed at /app/src/DTO/DTOValueResolver.php:44)"} []
[2024-06-20T16:45:18.594141+00:00] request.INFO: Matched route "price". {"route":"price","route_parameters":{"_route":"price","_controller":"App\\Controller\\PriceController::index"},"request_uri":"http://localhost/api/price","method":"GET"} []
[2024-06-20T16:45:18.644340+00:00] app.INFO: An exception occurred in ValidationException scenario {"exception":"[object] (App\\Exception\\ValidationException(code: 0): Request validation failed at /app/src/DTO/DTOValueResolver.php:44)"} []
[2024-06-20T16:46:47.366248+00:00] php.DEBUG: Warning: filemtime(): stat failed for /app/var/cache/de_/App_KernelDevDebugContainer.php {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/app/vendor/symfony/config/Resource/FileResource.php","line":58,"trace":[{"file":"/app/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":44,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2024-06-20T16:46:47.395484+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:47:14.312713+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:47:24.673262+00:00] request.INFO: Matched route "price". {"route":"price","route_parameters":{"_route":"price","_controller":"App\\Controller\\PriceController::index"},"request_uri":"http://localhost/api/price","method":"GET"} []
[2024-06-20T16:47:24.726634+00:00] app.INFO: An exception occurred in ValidationException scenario {"exception":"[object] (App\\Exception\\ValidationException(code: 0): Request validation failed at /app/src/DTO/DTOValueResolver.php:44)"} []
[2024-06-20T16:48:00.769564+00:00] php.DEBUG: Warning: filemtime(): stat failed for /app/var/cache/de_/App_KernelDevDebugContainer.php {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/app/vendor/symfony/config/Resource/FileResource.php","line":58,"trace":[{"file":"/app/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":44,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2024-06-20T16:48:07.508469+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:48:07.513718+00:00] app.ERROR: An exception occurred in Default scenario {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/doc\" is not callable: Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:98)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"nelmio_api_doc.controller.swagger_ui\" does neither exist as service nor as class. at /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"nelmio_api_doc.controller.swagger_ui\" not found at /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php:153)"} []
[2024-06-20T16:48:32.425315+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T16:48:39.360703+00:00] request.INFO: Matched route "price". {"route":"price","route_parameters":{"_route":"price","_controller":"App\\Controller\\PriceController::index"},"request_uri":"http://localhost/api/price","method":"GET"} []
[2024-06-20T16:48:39.418483+00:00] app.INFO: An exception occurred in ValidationException scenario {"exception":"[object] (App\\Exception\\ValidationException(code: 0): Request validation failed at /app/src/DTO/DTOValueResolver.php:44)"} []
[2024-06-20T21:16:21.154851+00:00] app.INFO: HttpException {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/\" at /app/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:181)"} []
[2024-06-20T21:16:28.194615+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T21:16:34.102787+00:00] request.INFO: Matched route "price". {"route":"price","route_parameters":{"_route":"price","_controller":"App\\Controller\\PriceController::index"},"request_uri":"http://localhost/api/price","method":"GET"} []
[2024-06-20T21:16:34.167523+00:00] app.INFO: An exception occurred in ValidationException scenario {"exception":"[object] (App\\Exception\\ValidationException(code: 0): Request validation failed at /app/src/DTO/DTOValueResolver.php:44)"} []
[2024-06-20T21:17:06.553049+00:00] request.INFO: Matched route "price". {"route":"price","route_parameters":{"_route":"price","_controller":"App\\Controller\\PriceController::index"},"request_uri":"http://localhost/api/price","method":"GET"} []
[2024-06-20T21:17:06.609920+00:00] app.INFO: An exception occurred in ValidationException scenario {"exception":"[object] (App\\Exception\\ValidationException(code: 0): Request validation failed at /app/src/DTO/DTOValueResolver.php:44)"} []
[2024-06-20T21:17:51.182400+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T21:18:06.305962+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T21:34:59.927109+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
[2024-06-20T21:56:01.435256+00:00] request.INFO: Matched route "app.swagger_ui". {"route":"app.swagger_ui","route_parameters":{"_route":"app.swagger_ui","_controller":"nelmio_api_doc.controller.swagger_ui"},"request_uri":"http://localhost/api/doc","method":"GET"} []
